### ISSUE TITLE
Failed To Load Profile

### ISSUE THREAD

**Issue by RitzDx** [RealMCoded/LunarRec#14]
**Describe the bug**
Rec room load up but fails to load profiles

**To Reproduce**
modify build, start server and build, fail to load profiles

**Expected behavior**
To work

**Screenshots**
im too lazy too put a screen shot so here is what it says in the console
C:\Users\jonny\Desktop\LunarRec-master\src\routes\players.js:38
    if (allow2016AndEarly2017) {
    ^

ReferenceError: allow2016AndEarly2017 is not defined
    at C:\Users\jonny\Desktop\LunarRec-master\src\routes\players.js:38:5
    at Layer.handle [as handle_request] (C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Users\jonny\Desktop\LunarRec-master\node_modules\express\lib\router\index.js:47:12)

Node.js v20.15.1

**System Information:**
 - Server OS: windows 10
 - LunarRec Version: 0.1.0(i think)
 - LunarRec Commit 7bcd97c

 - Rec Room Version: February 23rd 2017 

**Additional context**
N/A

**Comment by CrypticBren** [comment]
the dev seems to have forgotten to import it from the config you will most likely have to wait for a fix

**Comment by RitzDx** [comment]
Alright
